### ISSUE TITLE
Support python 3.12

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-comp#483]
See the [3.12 stable release announcement](https://www.python.org/downloads/release/python-3120/)

**Comment by cyschneck** [comment]
There is a Github shield for python packages from PyPi that can make it readable at a glance for the README

`https://img.shields.io/pypi/pyversions/geocat-comp`

![PyPi-Versions](https://img.shields.io/pypi/pyversions/geocat-comp)

**Comment by cyschneck** [comment]
- [ ] Update build environments (setup.cfg, docs.yml, environment.yml)
- [ ] Workflow releases and pytests (ci-release.yml, ci.yml)

**Comment by cyschneck** [comment]
Numba Python 3.12 support is still a work-in-progress as of https://github.com/numba/numba/issues/9197

Currently throws:
```
RuntimeError: Cannot install on Python version 3.12.0; only versions >=3.8,<3.12 are supported
```

**Comment by cyschneck** [comment]
Numba PR for Python 3.12 support is merged and will be packaged with the upcoming Numba 0.59 release

**Comment by kafitzgerald** [comment]
I expressed a bit of concern about dropping 3.9 earlier, but I think I've been swayed by the guidance laid out in SPEC0 and adoption of that by the major scientific packages.  And npl-2023b has made it to Python 3.10 at least.  

Here's the related [xarray convo](https://github.com/pydata/xarray/discussions/8237) about version support and a link to [SPEC 0](https://scientific-python.org/specs/spec-0000/).

**Comment by cyschneck** [comment]
Numba on a [code freeze](https://github.com/numba/numba/issues/9197#issuecomment-1865218765) until January 14th. Release candidate 0.59.0rc1 will add Python 3.12

**Comment by anissa111** [comment]
If you install the release candidate and run the tests locally, does everything work?

**Comment by cyschneck** [comment]
I will give it a look

**Comment by cyschneck** [comment]
The release candidate is looking good, but won't be able to test against the full testing suite until eofs is updated to work with 3.12 as well

```
$ pip install eofs
Collecting eofs
  Using cached eofs-1.4.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/setup.py", line 38, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-jlchx2g0/eofs_bd6309de443d4c75b63ad3c4db8f197b/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
```

Same reason a pip install of geocat-comp on python3.12 isn't currently possible

```
$ pip install geocat.comp
Collecting geocat.comp
  Downloading geocat.comp-2023.3.1-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 kB 894.0 kB/s eta 0:00:00
Requirement already satisfied: cf-xarray>=0.3.1 in /home/user/miniconda3/envs/geocat_comp_build_312/lib/python3.12/site-packages (from geocat.comp) (0.8.7)
Requirement already satisfied: cftime in /home/user/miniconda3/envs/geocat_comp_build_312/lib/python3.12/site-packages (from geocat.comp) (1.6.3)
Requirement already satisfied: dask[array] in /home/user/miniconda3/envs/geocat_comp_build_312/lib/python3.12/site-packages (from geocat.comp) (2023.12.1)
Collecting eofs (from geocat.comp)
  Using cached eofs-1.4.0.tar.gz (1.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-ve2rfu6t/eofs_205c04cd9326442397bf7a808029cb37/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ve2rfu6t/eofs_205c04cd9326442397bf7a808029cb37/setup.py", line 38, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ve2rfu6t/eofs_205c04cd9326442397bf7a808029cb37/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-ve2rfu6t/eofs_205c04cd9326442397bf7a808029cb37/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ve2rfu6t/eofs_205c04cd9326442397bf7a808029cb37/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
```

I'll look into it more now that numba is looking good. There is a current issue open for this eofs issue (https://github.com/ajdawson/eofs/issues/141), but it's a common issue in packages because of the new deprecations in Python 3.12
